### ISSUE TITLE
unexpected end of file error

### ISSUE THREAD

**Issue by sabrsyed** [open2c/distiller-nf#156]
Hi, 

I'm trying to analyze some Capture Hi-C data from GEO but am encountering the following error: 

_[0b/fc749c] NOTE: Process `chunk_fastqs (library:D0-capturehic__mm10 run:lane2)` terminated with an error exit status (1) -- Execution is retried (2)
[0e/a637c7] Re-submitted process > chunk_fastqs (library:D0-capturehic__mm10 run:lane2)
[b2/c1442f] NOTE: Process `chunk_fastqs (library:D0-capturehic__mm10 run:lane6)` terminated with an error exit status (1) -- Execution is retried (1)
[be/276f57] Re-submitted process > chunk_fastqs (library:D0-capturehic__mm10 run:lane6)
[00/b1c99e] NOTE: Process `chunk_fastqs (library:D0-capturehic__mm10 run:lane7)` terminated with an error exit status (1) -- Execution is retried (2)
[a4/c0ea33] Re-submitted process > chunk_fastqs (library:D0-capturehic__mm10 run:lane7)
ERROR ~ Error executing process > 'chunk_fastqs (library:D0-capturehic__mm10 run:lane4)'

Caused by:
  Process `chunk_fastqs (library:D0-capturehic__mm10 run:lane4)` terminated with an error exit status (1)

Command executed:

  zcat d0_n4_SRR5297633_R1_001.fastq.gz | split -l 112000000 -d         --filter 'pbgzip -c -n 4 > $FILE.1.fastq.gz' -         D0-capturehic__mm10.lane4.
  zcat d0_n4_SRR5297633_R2_001.fastq.gz | split -l 112000000 -d         --filter 'pbgzip -c -n 4 > $FILE.2.fastq.gz' -         D0-capturehic__mm10.lane4.

Command exit status:
  1

Command output:
  (empty)

Command error:
  ESC[33mWARNING: Non existent bind point (directory) in container: '/lsf'
  ESC[0mESC[33mWARNING: Non existent bind point (directory) in container: '/share'
  ESC[0mESC[33mWARNING: Non existent bind point (directory) in container: '/project'
  ESC[0mESC[33mWARNING: Non existent bind point (directory) in container: '/farline'
  ESC[0mESC[33mWARNING: Not mounting requested bind point (already mounted in container): /nl
  ESC[0m+ zcat d0_n4_SRR5297633_R1_001.fastq.gz
  + split -l 112000000 -d --filter 'pbgzip -c -n 4 > $FILE.1.fastq.gz' - D0-capturehic__mm10.lane4.
 
  gzip: d0_n4_SRR5297633_R1_001.fastq.gz: unexpected end of file_

The FASTQ files look like this:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/32850198/94481467-bc944f80-01a5-11eb-8e87-d6faa74c71f0.png">
 
And it ends like this: 
BBBFFFFFFFFFFIFIBFFFFIFIIFIIIIIFFFFFFFFFFFFFBBFFFFF<F77BFFFBBFF###########'0000<

Any help would be appreciated!

**Comment by Phlya** [comment]
I'm not sure what those binding errors are about (is it some docker stuff?), but are you sure your fastqs are not corrupted? Usually this sort of errors is caused by truncated files. For example, what happens if you do `d0_n4_SRR5297633_R1_001.fastq.gz | wc -l`? Should just give the number of lines in your file (which is 4x number of reads), but it will give a similar error if the file is corrupted in some way.

**Comment by sabrsyed** [comment]
Oh, thanks! 

I have 14 files and it seems that 4 are throwing this error when i do zcat x.fastq.gz | wc -l

**Comment by golobor** [comment]
+1 to @Phlya 's comment - i'd check that fastq files contain an equal number of strings. In case fastq is broken, you may try using https://github.com/nunofonseca/fastq_utils filter_pair command to fix your files. I haven't used it yet, but the description looks like what you'd need.

**Comment by golobor** [comment]
oh, I'm sorry, I didn't read your comment correctly. Yes, this looks like your files got corrupted during transfer. :(

**Comment by golobor** [comment]
assuming it got resolved! please feel free to re-open otherwise
