### ISSUE TITLE
distiller-nf run failed at executing process > 'bin_zoom_library_pairs‘

### ISSUE THREAD

**Issue by hzjsxu** [open2c/distiller-nf#167]
Some errors occurred when using distiller to process HiC data as follows. How can I solve it ?

N E X T F L O W  ~  version 19.01.0
Launching `/xxx/biosoft/distiller-nf/distiller.nf` [intergalactic_rosalind] - revision: 0edeab7502
WARN: There's no process matching config selector: download_sra
[warm up] executor > lsf
[89/dce59a] Submitted process > map_parse_sort_chunks (library:R4 run:lane1 chunk:0)
[0b/c1b654] Submitted process > map_parse_sort_chunks (library:N3 run:lane1 chunk:0)
[c5/914d5a] Submitted process > map_parse_sort_chunks (library:212R run:lane1 chunk:0)
[1b/17881e] Submitted process > map_parse_sort_chunks (library:N2 run:lane1 chunk:0)
[9a/f22943] Submitted process > map_parse_sort_chunks (library:B2 run:lane1 chunk:0)
[35/3d3403] Submitted process > map_parse_sort_chunks (library:R1 run:lane1 chunk:0)
[98/66f2c9] Submitted process > merge_dedup_splitbam (library:R4)
[b7/1e921a] Submitted process > merge_dedup_splitbam (library:212R)
[25/03c4b8] Submitted process > merge_dedup_splitbam (library:N3)
[b1/1946a5] Submitted process > merge_dedup_splitbam (library:N2)
[fe/987788] Submitted process > merge_dedup_splitbam (library:B2)
[54/e1ecc5] Submitted process > merge_dedup_splitbam (library:R1)
[d9/f840c8] Submitted process > bin_zoom_library_pairs (library:R4 filter:mapq_30)
[95/96ba83] Submitted process > bin_zoom_library_pairs (library:R4 filter:no_filter)
ERROR ~ Error executing process > 'bin_zoom_library_pairs (library:212R filter:mapq_30)'

Caused by:
  Cannot invoke method join() on null object

Source block:
  def res_str = params['bin'].resolutions.join(',')
  def balance_options = params['bin'].get('balance_options','')
  balance_options = ( balance_options ? "--balance-args \"${balance_options}\"": "")
  def balance_flag = ( params['bin'].get('balance','true').toBoolean() ? "--balance ${balance_options}" : " " )
  def filter_command = (filter_expr == '' ? '' : "| pairtools select '${filter_expr}'")
  """
  ${pairsgz_decompress_command} ${pairs_lib} ${filter_command} | cooler cload pairs \
      -c1 2 -p1 3 -c2 4 -p2 5 \
      --assembly ${ASSEMBLY_NAME} \
      ${chrom_sizes}:${MIN_RES} - ${library}.${ASSEMBLY_NAME}.${filter_name}.${MIN_RES}.cool
  
  cooler zoomify \
      --nproc ${task.cpus} \
      --out ${library}.${ASSEMBLY_NAME}.${filter_name}.${MIN_RES}.mcool \
      --resolutions ${res_str} \
      ${balance_flag} \
      ${library}.${ASSEMBLY_NAME}.${filter_name}.${MIN_RES}.cool
  
  """

**Comment by golobor** [comment]
hm, this looks weird!
Looks like resolutions were not read from the params file.
From a quick glance, my first suggestion would be to check the config.yaml
file thoroughly (that is, check tabulation, closed quotes, etc) - it seems
that some section didn't get read.
