### ISSUE TITLE
Iterative mapping

### ISSUE THREAD

**Issue by chorzow** [open2c/distiller-nf#173]
Hello everyone,

I was wondering if distiller uses iterative mapping strategy as implemented in hiclib pipeline. If it does, is it possible to change minimal sequence length and/or truncation length?

Thanks in advance!

**Comment by Phlya** [comment]
Hi, no, distiller doesn't use iterative mapping. It maps using bwa-mem, with local alignment.

**Comment by chorzow** [comment]
Thanks for the information! Closing.
